services:
  fastapi:
    container_name: fastapi
    expose:
      - 8000
    build: ./app
    depends_on:
      - postgres
    env_file:
      - app/.env
    restart: always
    command: bash -c "
      alembic upgrade head &&
      gunicorn -k uvicorn.workers.UvicornWorker app.main:app -b 0.0.0.0:8000"

  postgres:
    image: postgres:latest
    expose:
      - 5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - app/.env
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=ASDGmp;oq234980jfdowsij
    restart: always

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - fastapi

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./data/backups:/backups
    depends_on:
      - postgres
    env_file:
      - app/.env
