name: test-template

services:
  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test-template

networks:
  test-template:
    name: test-template
