name: test

services:
  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test

networks:
  test:
    name: test
