"""add_search_history

Revision ID: c7413fabaae7
Revises: f8bc58120f2f
Create Date: 2024-11-17 21:13:23.153696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7413fabaae7'
down_revision = 'f8bc58120f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
