"""New column 'job_title'

Revision ID: 6467e5f44c79
Revises: 7e40e824cfbe
Create Date: 2024-12-12 21:51:16.451201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6467e5f44c79'
down_revision = '7e40e824cfbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_request', sa.Column('job_title', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_request', 'job_title')
    # ### end Alembic commands ###
