"""add_search_history2.0

Revision ID: e017f3cba929
Revises: f8bc58120f2f
Create Date: 2024-11-29 23:53:33.047811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e017f3cba929'
down_revision = 'f8bc58120f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
